NAME = ft_display_file
SRC = ft_display_file.c
FLAGS = -Wall -Wextra -Werror -o

all: $(NAME)

$(NAME):
	gcc $(FLAGS) $(NAME) $(SRC)

clean:
	/bin/rm -f *.o

fclean: clean
	/bin/rm -f $(NAME)

re: fclean all
